# Exception context
if(DC_EXCEPTIONS_CONTEXT)
    set(DC_EXCEPTION_CONTEXT_IMPLEMENTATION "unix")
else()
    set(DC_EXCEPTION_CONTEXT_IMPLEMENTATION "nop")
endif()


# Machien context
set(DC_MACHINE_CONTEXT_IMPLEMENTATION "nop")

if((CMAKE_HOST_SYSTEM_PROCESSOR STREQUAL "aarch64") OR (CMAKE_HOST_SYSTEM_PROCESSOR STREQUAL "arm") OR (CMAKE_HOST_SYSTEM_PROCESSOR STREQUAL "arm64"))
    set(DC_MACHINE_CONTEXT_IMPLEMENTATION "armv8_a_64")
endif()

if(CMAKE_HOST_SYSTEM_PROCESSOR STREQUAL "x86_64")
    set(DC_MACHINE_CONTEXT_IMPLEMENTATION "x86_64")
endif()

if(DC_USE_UCONTEXT)
    set(DC_MACHINE_CONTEXT_IMPLEMENTATION "ucontext")
endif()
